### ISSUE TITLE
How install in Linux

### ISSUE THREAD

**Issue by CarvalhoResearch** [CIDCO-dev/OpenSidescan#122]
Hello, thanks for developing opensidescan!
I would like to know how to install it on my linux mint, as I haven't found any tutorial yet.

**Comment by glabmoris** [comment]
Hi!
We do not support Linux binary builds for now.
You need to install opencv and QT, and open the QTCreator project inside the repo to compile it. 

This is currently the only workflow we support for our development purposes, however feel free to contribute anything that would make things easier in the matter. For example, we could easily integrate CMake to make the whole dependency management more palatable.

Cheers!

**Comment by patcmorneau** [comment]
> Hello, thanks for developing opensidescan!
> I would like to know how to install it on my linux mint, as I haven't found any tutorial yet.

install instruction are now available : https://github.com/CIDCO-dev/OpenSidescan/blob/master/INSTALL.md
