### ISSUE TITLE
Forced close when importing file

### ISSUE THREAD

**Issue by Peck117** [CIDCO-dev/OpenSidescan#125]
When ever I try to import and XTF file the program closes immediately and without warning. Any idea why this might be happeing?

**Comment by mapping-abc** [comment]
I am having the same issue. Any solutions?

**Comment by glabmoris** [comment]
Hi,
This can happen with new XTF dialects that are not yet supported. If you can, please send me the problematic XTF file at guillaume.morissette@cidco.ca so we can add support.

Thank you!
