### ISSUE TITLE
Georéférencer correctement SidescanPing

### ISSUE THREAD

**Issue by glabmoris** [CIDCO-dev/OpenSidescan#28]
En ce moment, lorsqu'on géoréférence un ping, on prend la position GNSS qui est associée au ping, et non le vecteur résultant de l'addition des vecteurs position, distance au poisson, et du ping. Cette mesure n'est donc pas précise du tout.

**Comment by JordanMcManus** [comment]
Il y a un logiciel qui s'appelle SonarWiz qui utilise 3 méthodes différentes:
[Methode pour layback](https://chesapeaketech.com/wp-content/uploads/docs/SonarWiz%207.3%20User%20Guide%20HTM/HTML/layback___offsets.htm?ms=AgQAAAAAAAAAAAAAAAACAg%3D%3D&st=MA%3D%3D&sct=MA%3D%3D&mw=MjQw)

Methode | Hypothèses | Info requise
-- | -- | --
Pythagoras Theorem | Towfish directly behind vessel | Towfish DepthCable Out
Look-up Tables | Towfish directly behind vesselNo (along track) effect from currents | Tow Cable typeDepressor type (if any)Cable OutVessel speed
Horse & Cart | Towfish directly behind vessel | Cable Out
