### ISSUE TITLE
Erreur de link sur windows

### ISSUE THREAD

**Issue by HugoValcourt** [CIDCO-dev/OpenSidescan#4]
![Screenshot from 2019-08-21 16-28-09](https://user-images.githubusercontent.com/36771930/63466196-c7bc6e00-c430-11e9-9b30-e4a2c997dc76.png)
![Screenshot from 2019-08-21 16-28-24](https://user-images.githubusercontent.com/36771930/63466197-c7bc6e00-c430-11e9-886c-2bd3057222b5.png)

XtfParser.cpp ne trouve pas une méthode dans le .hpp

**Comment by glabmoris** [comment]
htonl() est une fonction de la suite socket. Sous Windows, il faut inclure <winsock.h> vianune directive de compilation conditionnelle (#ifdef _WIN64)

Ya malheureusement pas de super standard, et des fois faut les setters manuellement dans la ligne de compilation (-D sous gcc/g++, /D dans cl messemble...rtm)

Voici les macros "standard-ish" pour usage futur:
https://www.boost.org/doc/libs/1_71_0/doc/html/predef/reference.html#predef.reference.boost_os_operating_system_macrosf

**Comment by HugoValcourt** [comment]
C'était ça! J'avais déjà le check pour windows (#ifdef _WIN64) et #include <winsock.h> mais il manquait une liaison de plus pour le fichier .lib 

#pragma comment(lib, Ws2_32.lib)
