### ISSUE TITLE
Save Image

### ISSUE THREAD

**Issue by HugoValcourt** [CIDCO-dev/OpenSidescan#5]
Est-ce que l'option 'Save Image' est supposer être gris comme ça ou c'est une erreur?
![Screenshot from 2019-08-22 09-06-14](https://user-images.githubusercontent.com/36771930/63517103-51654d80-c4bc-11e9-9f6a-eb8d537cde77.png)

C'est pareille sur Windows et Linux

**Comment by glabmoris** [comment]
Oui, Save Image a été remplacé par un bouton dans le tab de l'image
