### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by HugoValcourt** [CIDCO-dev/OpenSidescan#6]
Quand le gui ce fait fermer avec l'option File->Quit il y à une segmentation fault.

**Comment by glabmoris** [comment]
La branche master laggait sur ma branche. Vérifier si c'est toujours le cas depuis #7

**Comment by HugoValcourt** [comment]
J'ai encore une segfault de mon côté après m'avoir mis à jour.
Voici les dernière ligne du console output:
`
Generating images for 3 channels
Channel 0
Rows: 2009 Cols: 1024
Channel 1
Rows: 2009 Cols: 1024
Channel 2
Rows: 2009 Cols: 1024
Segmentation fault
`
