### ISSUE TITLE
Show Microfeatures doesn't work anymore

### ISSUE THREAD

**Issue by glabmoris** [CIDCO-dev/OpenSidescan#69]
When detecting regions of interest, the "show microfeatures" option is a no-op

**Comment by JordanMcManus** [comment]
Can you add a version number where this was working, I should be able to figure out which change broke it.

**Comment by glabmoris** [comment]
Nothing comes to mind. Installer executables are on the Jenkins box should you need to go down that road

**Comment by JordanMcManus** [comment]
I tested versions back to 0.1.22 (jan 13th with working installer) on windows and show micro features doesn't work.

I will checkout older versions from github and build locally to try to find a version where these work,

**Comment by JordanMcManus** [comment]
```
if(showFeatureMarkers){
        cv::drawKeypoints(image.getDisplayedImage(),combinedKeypoints,image.getDisplayedImage(),cv::Scalar(0,0,255),cv::DrawMatchesFlags::DRAW_RICH_KEYPOINTS);
    }
```

In debug mode, I can see that this is true (so the Microfeatures checkbox is detected as checked).

**Comment by JordanMcManus** [comment]
We can exclude @CBcidco's modification with workers and progress bars.

For the version on December 10 (before @CBcidco started), we can see in debug mode that

```
if(showFeatureMarkers){
        cv::drawKeypoints(image.getDisplayedImage(),combinedKeypoints,image.getDisplayedImage(),cv::Scalar(0,0,255),cv::DrawMatchesFlags::DRAW_RICH_KEYPOINTS);
}
```
is true when the show MicroFeatures is true, but still nothing is drawn.

**Comment by JordanMcManus** [comment]
The `OpencvHelper::draw(...)` starts with `img.resetDisplayedImage()`

Therefore microfeatures get erased.

I refactored the `SidescanImage` class to contain a vector of microfeatures (`cv::KeyPoints`).

Now they are visible.

Unfortunately, there is a conflict with the color scaling that I haven't yet resolved. I've tried to imitate the hack that is there for the bounding boxes, but it doesn't work.

**Comment by glabmoris** [comment]
Nice find! So it's related to the colorizing of the greyscale image?

**Comment by JordanMcManus** [comment]
No, not related. It was just the reset the cleared them.

**Comment by JordanMcManus** [comment]
The issue with color coding is a seperate one. I suggest we close this issue and open a new one to fix the color scale.

**Comment by glabmoris** [comment]
To be continued in #74
