### ISSUE TITLE
Color scale doesn't detect microfeature circle color

### ISSUE THREAD

**Issue by JordanMcManus** [CIDCO-dev/OpenSidescan#74]
When Microfeatures are active, the image is displayed in greyscale instead of golden scale.

**Comment by CBcidco** [comment]
In OpencvHelper::draw(), when showMicroFeatures is true, the function cv::drawKeypoints() is called.

Before the function call to cv::drawKeypoints(), cv::Mat displayedImage has type CV_8UC1. After the function call, it has type CV_8UC3. 

In QtHelper::cvMatToQImage(), the color map to get a golden scale is applied when the image type is 8UC1.

I will look at cv::drawKeypoints().

**Comment by CBcidco** [comment]
I modified the code:

I now apply a color map to the displayedImage in OpencvHelper::draw(). The type of the image is then CV_8UC3. cv::drawKeypoints() is applied on this image and the type remains CV_8UC3.

QtHelper::cvMatToQImage() receives an CV_8UC3 image and does not have to apply a color map.
