### ISSUE TITLE
Crash on New Project when sidescan file in active project

### ISSUE THREAD

**Issue by CBcidco** [CIDCO-dev/OpenSidescan#84]
Steps to reproduce: 

Import a sidescan file. Click on New Project in the toolbar (or through the menubar). Click on OK in the window to continue, OpenSidescan will crash or get stucked.

I went back to commit 366e9d on February 21st, and the problem is not there.

The problem is there in commit 63bb0c from March 22nd.

**Comment by glabmoris** [comment]
Quel fichier sidescan cause ceci?

**Comment by CBcidco** [comment]
Ce n'est pas dépendant du fichier sidescan. C'est un problème nouveau introduit entre les deux commits indiqués.

**Comment by JordanMcManus** [comment]
Je suis aussi capable de reproduire (dans mon cas j'ai utilisé plane1.xtf).

Lors du crash, j'ai vu un bad_alloc() exception qui a été lancé. 

L'ajout des attitudes dans les pings a causé qq problèmes (si y'a pas d'attitude dans l'image ça chie).

**Comment by glabmoris** [comment]
plane1.xtf n'a pas de packets de position. Est-ce que les modifs dans SidescanImager font que des packets de position / attitude sont nécessaires?

**Comment by JordanMcManus** [comment]
Théoriquement non, car l'interpolation a juste lieu si les `std::vector` qui contiennent les positions et les attitudes sont non-vides.

```
// If ping does not have an attitude and the attitudes vector is not empty: interpolate the attitude
                if(channels[i]->at(j)->getAttitude() == NULL && ! attitudes.empty()){

                    //find attitude for ping
                    while(attitudeIndex + 1 < attitudes.size() && attitudes[attitudeIndex+1].getTimestamp() < channels[i]->at(j)->getTimestamp() ){
                        attitudeIndex++;
                    }

                    if(attitudeIndex >= attitudes.size() - 1){
                        std::cerr << "No attitude data for ping" << std::endl;
                        break;
                    }

                    if(attitudes[attitudeIndex].getTimestamp() > channels[i]->at(j)->getTimestamp()){
                        std::cerr << "rejecting ping for attitude timestamp problem: " << channels[i]->at(j)->getTimestamp() << " " << attitudes[positionIndex].getTimestamp() << std::endl;
                        continue;
                    }

                    Attitude* pingAttitude = Interpolator::interpolateAttitude(attitudes[attitudeIndex], attitudes[attitudeIndex+1], channels[i]->at(j)->getTimestamp());

                    channels[i]->at(j)->setAttitude(pingAttitude);
                }
```

**Comment by JordanMcManus** [comment]
Dans le debugger, on a un SIGABRT à la ligne 225 de mainwindow.cpp

`tabs->clear();`

```
void MainWindow::updateSelectedFile(SidescanFile * newFile){

    selectedFile = newFile;
    selectedImage = NULL;

    tabs->clear(); //TODO: does this leak?
```

**Comment by glabmoris** [comment]
> Théoriquement non, car l'interpolation a juste lieu si les std::vector qui contiennent les positions et les attitudes sont non-vides.

Et si on n'a pas d'interpolation parcequ'on a aucune attitude/position? A-t-on une image vide?

**Comment by JordanMcManus** [comment]
L'image n'est pas vide.

Je pense que c'est plutot au niveau de la destruction (et non la création) des objets. Malheusement le debugger de Qt ne coopère pas trop et il plante quand on arrive à la ligne 225 de mainwindow.cpp, comme je l'ai dit plus haut.

**Comment by glabmoris** [comment]
Ok, balise ça comme il faut avec les tests en #85 et on avisera avec des tests UI si nécessaire
