### ISSUE TITLE
Detect object sous windows

### ISSUE THREAD

**Issue by JordanMcManus** [CIDCO-dev/OpenSidescan#99]
Sous linux, l'outil detect objects trouve l'avion dans le fichier plane1.xtf. 

Sous windows, il ne le trouve pas.

**Comment by glabmoris** [comment]
Est-ce que le comportement est le meme dans le logiciel OpenSidescan?

**Comment by JordanMcManus** [comment]
Oui, c'est par le GUI que j'ai noté le problème.

**Comment by glabmoris** [comment]
Faudrait baliser ça par un test unitaire

**Comment by JordanMcManus** [comment]
En effet.

Je viens de faire rouler les tests GUI tantôt. Y'en a 17 qui passent et 5 qui échouent. C'est une god class avec 3000 lignes de code et c'est plein de slots qui rendent ça difficile à suivre.

Je vais passer ça au coûteau de boucherie et prioriser le use case "Detect Objects". Je vais commencer par un test CATCH2 et voir c'est quoi le résultat sous windows.

**Comment by JordanMcManus** [comment]
Je n'ai pas réussi à faire partir OpenSideScan en mode debug sur windows (alors que c'est possible sous linux). Je soupçonne que les librairies qui sont packagés avec openCV sur windows n'inclus pas celle en debug (le folder est vide sous windows).

Je vais me partir une machine virtuelle windows et voir compiler moi même les librairies.
